# Generated by Django 5.1.3 on 2024-11-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_unit_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund_cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name', models.CharField(max_length=50)),
                ('fund_code', models.CharField(max_length=50)),
            ],
        ),
    ]
