# Generated by Django 5.1.3 on 2024-11-07 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_fund_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_num', models.CharField(max_length=100)),
                ('stock_name', models.CharField(max_length=100)),
                ('stock_qty', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.unit_list')),
            ],
        ),
    ]
